{% set name = "pastas" %}
{% set version = "0.13.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/pastas/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 872475032392d152e5c2d1c0a1b8ba262d16f49b3ebdafca33e49c477bff658b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - numpy >=1.10
    - pip
    - python >=3.5
  run:
    - matplotlib >=2.0
    - {{ pin_compatible('numpy') }}
    - pandas >=0.22
    - python >=3.5
    - scipy >=1.0

test:
  imports:
    - pastas
    - pastas.io
    - pastas.project
    - pastas.read
    - pastas.stats

about:
  home: https://github.com/pastas/pastas
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Applied System TimeSeries Analysis Software
  doc_url: http://pastas.readthedocs.io
  dev_url: https://github.com/pastas/pastas

extra:
  recipe-maintainers:
    - jentjr
