travis:
  secure:
    BINSTAR_TOKEN: Vx03zVD8evlXDYC56q/2ToQJcUgGYieTklGvGnjxpVvkKFUqb+EuNofsyZFWW/nO5Uzc4h31XPSIhmrggpfs5/tMvZ8eqrgVmPfTk4RcA9N7eSlhbLKRA+qEYqDyP7vHEBKPLYjOXqqONicmfs79lXNlVBUWw2KHJwO/QCw1nSsMGAzSAgt50BLbNpnxwDwrPmp+BR6ViH1M2BEozx3DteZXIrYuDch2Y1vkmTFI2cBsia5/c0tC+qmDKJNLYJ4KQoHXIxhWHfsW1EMiKLQJOGNtBcGr9KAeeETWXQVMS+zSTDn45MJHhYDrRMcYWCSR5aaFw/I2Xwio/E/9idp2pIIkKYLT/dHEty/4ahaL5LMZ/1pbz+fAEVjA1qKlZHiOEtE5HhbGecJNT8cO+2uUzGD2NhFA2TJtg0pxuQtYar6mjSRLJrU3IakVrDXcEa/o5xYi/fU/LzbsxAwng5ioolewkdrqH0blz/Y+bKz3MKYDm/oyLnb0h5pTd95mBqmBGjrDJ0O2uAQFWUYx7xgRem70dRY/rnT2o8fpUOjd5fZY7TdZf2ln1ZDXrkXv8GejqeavXDgBmvl5Cm9BRjwTRSx60CU6+7zqIw6xjtF6WWcxwT3S3/PfVgJFoUaAitbWdlbZ//kWqZq4LMPVxQ2pvRZ9qvsNTznz89lBcA/0Ztw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
